"""Initial schema with all 9 UTIP tables

Revision ID: 34f6230c63c4
Revises: 
Create Date: 2026-01-17 22:14:55.690875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f6230c63c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_techniques',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cve_techniques_cve_id', 'cve_techniques', ['cve_id'], unique=False)
    op.create_index('idx_cve_techniques_technique_id', 'cve_techniques', ['technique_id'], unique=False)
    op.create_table('layers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threat_actors',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threat_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('PDF', 'STIX', 'TEXT', name='sourcetype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETE', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('uploaded_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vulnerability_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('scan_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actor_techniques',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.String(length=50), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['threat_actors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_actor_techniques_actor_id', 'actor_techniques', ['actor_id'], unique=False)
    op.create_index('idx_actor_techniques_technique_id', 'actor_techniques', ['technique_id'], unique=False)
    op.create_table('extracted_techniques',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.Enum('REGEX', 'LLM', name='extractionmethod'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['threat_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_extracted_techniques_report_id', 'extracted_techniques', ['report_id'], unique=False)
    op.create_index('idx_extracted_techniques_technique_id', 'extracted_techniques', ['technique_id'], unique=False)
    op.create_table('layer_techniques',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('layer_id', sa.UUID(), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('color', sa.Enum('YELLOW', 'BLUE', 'RED', name='techniquecolor'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('from_intel', sa.Integer(), nullable=False),
    sa.Column('from_vuln', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['layers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_layer_techniques_layer_id', 'layer_techniques', ['layer_id'], unique=False)
    op.create_index('idx_layer_techniques_technique_id', 'layer_techniques', ['technique_id'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('asset', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['vulnerability_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vulnerabilities_cve_id', 'vulnerabilities', ['cve_id'], unique=False)
    op.create_index('idx_vulnerabilities_scan_id', 'vulnerabilities', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vulnerabilities_scan_id', table_name='vulnerabilities')
    op.drop_index('idx_vulnerabilities_cve_id', table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index('idx_layer_techniques_technique_id', table_name='layer_techniques')
    op.drop_index('idx_layer_techniques_layer_id', table_name='layer_techniques')
    op.drop_table('layer_techniques')
    op.drop_index('idx_extracted_techniques_technique_id', table_name='extracted_techniques')
    op.drop_index('idx_extracted_techniques_report_id', table_name='extracted_techniques')
    op.drop_table('extracted_techniques')
    op.drop_index('idx_actor_techniques_technique_id', table_name='actor_techniques')
    op.drop_index('idx_actor_techniques_actor_id', table_name='actor_techniques')
    op.drop_table('actor_techniques')
    op.drop_table('vulnerability_scans')
    op.drop_table('threat_reports')
    op.drop_table('threat_actors')
    op.drop_table('layers')
    op.drop_index('idx_cve_techniques_technique_id', table_name='cve_techniques')
    op.drop_index('idx_cve_techniques_cve_id', table_name='cve_techniques')
    op.drop_table('cve_techniques')
    # ### end Alembic commands ###
