"""Add additional fields to vulnerabilities table

Revision ID: d04ec1cfe451
Revises: 34f6230c63c4
Create Date: 2026-01-18 13:52:39.843757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04ec1cfe451'
down_revision: Union[str, None] = '34f6230c63c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('cvss_score', sa.Float(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('port', sa.String(length=20), nullable=True))
    op.add_column('vulnerabilities', sa.Column('plugin_id', sa.String(length=20), nullable=True))
    op.add_column('vulnerabilities', sa.Column('plugin_name', sa.String(length=500), nullable=True))
    op.add_column('vulnerabilities', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('solution', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'solution')
    op.drop_column('vulnerabilities', 'description')
    op.drop_column('vulnerabilities', 'plugin_name')
    op.drop_column('vulnerabilities', 'plugin_id')
    op.drop_column('vulnerabilities', 'port')
    op.drop_column('vulnerabilities', 'cvss_score')
    # ### end Alembic commands ###
